"""add budget

Revision ID: 0c0102c399c6
Revises: ff6b016bd4e6
Create Date: 2024-06-08 18:07:34.750956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0102c399c6'
down_revision: Union[str, None] = 'ff6b016bd4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('budget', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_companies_budget'), 'companies', ['budget'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_budget'), table_name='companies')
    op.drop_column('companies', 'budget')
    # ### end Alembic commands ###
