"""sepetang

Revision ID: cbcd63f0ab57
Revises: cf8d822295f1
Create Date: 2024-06-08 17:04:28.387870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd63f0ab57'
down_revision: Union[str, None] = 'cf8d822295f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_description'), 'companies', ['description'], unique=False)
    op.create_index(op.f('ix_companies_established_year'), 'companies', ['established_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_established_year'), table_name='companies')
    op.drop_index(op.f('ix_companies_description'), table_name='companies')
    # ### end Alembic commands ###
